---
title: "Reproducible Research: Peer Assessment 1"
output:
  html_document:
    keep_md: true
---


## Loading and preprocessing the data

```{r}
if (!file.exists("activity.csv")) {
  unzip("activity.zip")  
}
data = read.csv("activity.csv")
complete = data[complete.cases(data),]
```

## What is mean total number of steps taken per day?

```{r echo=TRUE}
# Calculate the total number of steps taken per day
steps_per_day = aggregate(complete$steps, by=list(Date=complete$date), FUN=sum)
head(steps_per_day)

# Make a histogram of the total number of steps taken each day
hist(steps_per_day$x, xlab="Total steps", main="Histogram: Total number of steps per day")

# Calculate and report the mean and median of the total number of steps taken per day
print(c(mean(steps_per_day$x), median(steps_per_day$x)))
```


## What is the average daily activity pattern?

```{r echo=TRUE}
# Make a time series plot (i.e. type = "l") of the 5-minute interval (x-axis)
# and the average number of steps taken, averaged across all days (y-axis)
interval_averages = aggregate(complete$steps, by=list(interval=complete$interval), FUN=mean)
head(interval_averages)

plot(interval_averages$interval, interval_averages$x, type="l", xlab="Interval", ylab="steps")

# Which 5-minute interval, on average across all the days in the dataset,
# contains the maximum number of steps?
interval_averages[which(interval_averages$x == max(interval_averages$x)),"interval"]
```


## Imputing missing values

```{r echo=TRUE}
# Calculate and report the total number of missing values in the dataset (i.e.
# the total number of rows with NAs)
sum(is.na(data$steps))

# Devise a strategy for filling in all of the missing values in the dataset.
# The strategy does not need to be sophisticated. For example, you could use
# the mean/median for that day, or the mean for that 5-minute interval, etc.

# Actual strategy used:
# Just use the nr 0

# Create a new dataset that is equal to the original dataset but with the
# missing data filled in.

imputed_data <- data
imputed_data$steps[is.na(imputed_data$steps)] <- 0
head(imputed_data)

# Make a histogram of the total number of steps taken each day

# Calculate the total number of steps taken per day
imputed_steps_per_day = aggregate(imputed_data$steps, by=list(Date=imputed_data$date), FUN=sum)
head(imputed_steps_per_day)

# Make a histogram of the total number of steps taken each day
hist(imputed_steps_per_day$x, xlab="Total steps", main="Histogram: Total number of steps per day")

# Calculate and report the mean and median total number of steps taken per day.
print(c(mean(imputed_steps_per_day$x), median(imputed_steps_per_day$x)))
```


## Are there differences in activity patterns between weekdays and weekends?

```{r echo=TRUE}
# Create a new factor variable in the dataset with two levels – “weekday” and
# “weekend” indicating whether a given date is a weekday or weekend day.

complete$daytype = as.factor(ifelse(weekdays(as.Date(complete$date)) %in% c("Saturday", "Sunday"), "weekend", "weekday"))

# Make a panel plot containing a time series plot (i.e. type = "l") of the
# 5-minute interval (x-axis) and the average number of steps taken, averaged
# across all weekday days or weekend days (y-axis).

weekends = complete[which(complete$daytype=="weekend"),]
weekdays = complete[complete$daytype=="weekday",]

interval_averages_weekends = aggregate(weekends$steps, by=list(interval=weekends$interval), FUN=mean)
interval_averages_weekdays = aggregate(weekdays$steps, by=list(interval=weekdays$interval), FUN=mean)

par(mfrow=c(2,1))

# First weekends

plot(interval_averages_weekends$interval, interval_averages_weekends$x, type="l", xlab="Interval", ylab="steps", main="Weekends")

# Now weekdays

plot(interval_averages_weekdays$interval, interval_averages_weekdays$x, type="l", xlab="Interval", ylab="steps", main="Weekdays")
```
